language: python

cache: pip

# whitelist
branches:
  only:
    - master
    - prod

matrix:
  include:
    python: 3.6
    dist: xenial
    sudo: true

before_install:
  - sudo apt-get -y install libgfortran3

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - pytest --cov=orca

after_success:
  - codecov
  - mypy --ignore-missing-imports orca
