language: python

cache: pip

# whitelist
branches:
  only:
    - master
    - prod

jobs:
  include:
    python: 3.6
    dist: xenial

git:
  lfs_skip_smudge: true
  
before_install:
  - sudo apt-get -y install libgfortran3

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - wget https://www.astro.caltech.edu/~yuping/resources.tar.gz
  - tar -xvzf resources.tar.gz -C $TRAVIS_BUILD_DIR/distributed-pipeline/test
  - pytest --cov=orca
  - mypy --ignore-missing-imports orca

after_success:
  - bash <(curl -s https://codecov.io/bash)
