language: python

cache: pip

# only CI on the following branches 
branches:
  only:
    - main

jobs:
  include:
    python: 3.6
    dist: xenial

git:
  lfs_skip_smudge: true
  
before_install:
  - sudo apt-get -y install libgfortran3

install:
  - pip install pipenv
  - pipenv sync --dev

script:
  - wget --no-check-certificate http://www.tauceti.caltech.edu/yuping/resources.tar.gz
  - tar -xvzf resources.tar.gz -C $TRAVIS_BUILD_DIR/tests
  - pytest --cov=orca
  - mypy --ignore-missing-imports orca

after_success:
  - bash <(curl -s https://codecov.io/bash)
