language: python

cache: pip

matrix:
  include:
    python: 3.6
    dist: xenial
    sudo: true

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pytest --cov=orca

after_success:
  - codecov
  - mypy --ignore-missing-imports orca
